# The name of the workflow
name: CI

# Events that will cause the workflow to run
on:
  # When a pull request is opened or reopened or when the head branch of the pull request is updated
  pull_request:
    branches:
      - main
  # When you push a commit or tag, or when you create a repository from a template
  push:
    branches:
      - main
  # When a workflow is triggered manually, using the GitHub API, GitHub CLI, or GitHub browser interface
  workflow_dispatch:

# Ensure only one workflow runs at a time for each pull request or push to the main branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs, which run in parallel by default
jobs:
  build: # The unique identifier for the job
    name: Build # The name for the job, which is displayed in the GitHub UI
    runs-on: ${{ matrix.os }} # The type of machine to run the job on
    strategy: # Defines a matrix of different job configurations
      matrix:
        os: [ubuntu-latest]
        node_version: ["20.x"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js and cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Check code format with Prettier
        run: npm run format

      - name: Check code for linting errors with ESLint
        run: npm run lint

      - name: Type check with TypeScript
        run: npm run typecheck

      - name: Build with Vite
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./build/client
